version: 2.1

orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.0

jobs:

  validate:
    executor: node/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Validate CloudFormation
          command: |
            aws cloudformation validate-template \
              --template-body file://infra/template.json \
              --region us-east-1

  deploy:
    executor: node/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Deploy Cloudformation
          command: | 
            aws cloudformation deploy \
              --stack-name cf-templates \
              --template-file ./infra/template.json \
              --no-fail-on-empty-changeset \
              --parameter-overrides \
                BucketName=com.cuffney.cf-templates \
              --region us-east-1 && \ 
            aws s3 sync ./src s3://com.cuffney.cf-templates --delete

workflows:
  version: 2
  validate:
    jobs:
      - validate:
          context: cuffney
      - deploy:
          context: cuffney 
          requires:
            - validate
          filters:
            branches:
              only: master
