version: 2

defaults: &defaults
  docker: 
    - image: jcuffney/node-ci-image:1.0.25
  working_directory: ~/repo
  context: AWS

jobs:

  validate:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Validate CloudFormation
          command: cd infra/ && make validate

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploy Cloudformation
          command: | 
            cd infra/ && make deploy \
            aws s3 sync ./src s3://com.cuffney.cf-templates --delete

workflows:
  version: 2
  validate:
    jobs:
      - validate
      - deploy:
          requires:
            - validate
          filters:
            branches:
              only: master
